In [ ]:
student1 = [53,72,83,61,79]
student2 = [43,62,74,86,28]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("==========")

In [6]:
student1 = [53,72,83,61,79]
student2 = [43,62,74,86,28]
#變成數字串接
student1 + student2

[53, 72, 83, 61, 79, 43, 62, 74, 86, 28]

In [16]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([53,72,83,61,79])
student2:ndarray = np.array([43,62,74,86,28])

#可以做陣列運算，不需要使用for...in
totols:ndarray = student1 + student2
for total in totals:
    print(total)
    print("==========")


96
134
157
147
107


In [21]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndin,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [25]:
np.random.randint(50,101,size=(50,5))

array([[ 78,  79,  97,  68,  70],
       [ 87,  63,  81,  64,  78],
       [ 93,  61,  91,  76,  65],
       [ 50,  58,  98,  66,  58],
       [ 53,  77,  55,  66,  71],
       [ 81,  76,  62,  72,  69],
       [ 53,  93,  75,  90,  62],
       [100,  54,  87,  62,  68],
       [ 73,  54,  53,  66,  95],
       [ 95,  53,  54,  74,  50],
       [ 63,  77,  84,  84,  75],
       [ 77,  72,  91,  82,  83],
       [ 65,  61,  87,  64,  81],
       [ 73,  80,  96,  93,  76],
       [ 92,  85,  70,  83,  66],
       [ 93,  92,  51,  80,  77],
       [ 67,  72,  65,  96,  67],
       [ 52,  99,  50,  61,  93],
       [ 79,  79,  86,  50,  67],
       [ 81,  53,  73, 100,  92],
       [ 51,  81,  50,  90,  86],
       [ 52,  63,  64,  87,  83],
       [ 90,  50,  68,  50,  91],
       [ 66,  76,  67,  68,  80],
       [ 83,  50,  61,  96,  55],
       [ 70,  95,  56, 100,  92],
       [ 77,  93,  68,  50,  75],
       [ 55,  57,  57,  94,  68],
       [ 76,  72,  56,  77,  51],
       [ 55,  